### ISSUE TITLE
Tests Error because of missing data files

### ISSUE THREAD

**Issue by st-walker** [ocelot-collab/ocelot#164]
Hello friends,

One missing file in particular:

    FileNotFoundError: ./unit_tests/ebeam_test/section_track/accelerator/wakes/RF/mod_TESLA_MODULE_WAKE_TAYLOR.dat not found

This results in something like 15 errors.

Another single test fail:

     E           FileNotFoundError: ./unit_tests/ebeam_test/wake/wake_table.dat not found.

**Comment by sergey-tomin** [comment]
Just checked.  their are in repository. Apparently something wrong on your site. 
https://github.com/ocelot-collab/ocelot/blob/dev/unit_tests/ebeam_test/section_track/accelerator/wakes/RF/mod_TESLA_MODULE_WAKE_TAYLOR.dat

https://github.com/ocelot-collab/ocelot/blob/dev/unit_tests/ebeam_test/wake/wake_table.dat

**Comment by st-walker** [comment]
merged in #179
