### ISSUE TITLE
First test with Ocelot

### ISSUE THREAD

**Issue by hnakahara79** [ocelot-collab/ocelot#165]
Dear Developers,

This is going to be my first test with Ocelot. I have an electron beam with information of:

(1) x-position 
(2) y-position
(3) z-position
(4) Px, x-momentum
(5) Py, y-momentum
(6) Pz, z-momentum
(7) Particles weight

I have to study the transportation of this beam with beam-optics (Quadrupoles).

However, as a start, I would like to inject this electron beam in the Ocelot and would like to see its evolution in vacuum. After that I would like to proceed with the beam optics (gradually).

Please, could you guide me how I can study the electron beam evolution in vacuum. I want to do this in order to find the optimum position of the first magnet. 

Thank you.

**Comment by st-walker** [comment]
Hi @hnakahara79 , I would recommend you have a look at 

https://github.com/ocelot-collab/ocelot#tutorials

Perhaps it also makes sense to first consider the linear optics without particle tracking.

**Comment by hnakahara79** [comment]
Hi @st-walker , thank you for your quick reply. 

I will go through the tutorials. However, I may have lots of questions ....  I will start understanding the tutorials. 

Thank you.

**Comment by dmargarone** [comment]
Hi @st-walker ,

Following your suggestions, I am gradually practicing the tutorials. I can run and follow "**tutorial N1: Linear optics**" thoroughly, but when I am trying to run "**tutorial N2: Tracking**" I encountered with an error.

The error message was: 

**
from injector_lattice import *
ModuleNotFoundError: No module named 'injector_lattice'
**

Could you please help me to fix this error. 

Thanks a lot.

**Comment by hnakahara79** [comment]
Hi @st-walker,

I installed Ocelot manually on ubuntu linux OS (by downloading the last release zip file). Please note that I installed it with the command **python3 setup.py install**.

Then, I test the installation with the following line in a python script:  

import ocelot
print('ocelot:', ocelot.__version__)

**I received an error message as shown below:**

beam.py: module NUMEXPR is not installed. Install it if you want higher speed calculation.
optics.py: module NUMEXPR is not installed. Install it if you want higher speed calculation.
Traceback (most recent call last):
  File "/home/nakahara/Documents/ocelot-18.02.0/test1.py", line 13, in <module>
    import ocelot
  File "/home/nakahara/Documents/ocelot-18.02.0/ocelot/__init__.py", line 29, in <module>
    from ocelot.cpbd.magnetic_lattice import MagneticLattice
  File "/home/nakahara/Documents/ocelot-18.02.0/ocelot/cpbd/magnetic_lattice.py", line 122, in <module>
    class MagneticLattice:
  File "/home/nakahara/Documents/ocelot-18.02.0/ocelot/cpbd/magnetic_lattice.py", line 129, in MagneticLattice
    def __init__(self, sequence, start=None, stop=None, method=MethodTM()):
  File "/home/nakahara/Documents/ocelot-18.02.0/ocelot/cpbd/optics.py", line 686, in __init__
    self.sec_order_mult = SecondOrderMult()
  File "/home/nakahara/Documents/ocelot-18.02.0/ocelot/cpbd/optics.py", line 36, in __init__
    self.tmat_multip = nb.jit(nopython=True, parallel=True)(self.numba_apply)
  File "/home/nakahara/.local/lib/python3.10/site-packages/numba/core/decorators.py", line 220, in wrapper
    raise TypeError(
TypeError: The decorated object is not a function (got type <class 'method'>).

**Please, could you tell me how to fix this error.**

Thank you very much.

**Comment by hnakahara79** [comment]
Hi @st-walker, 

Once again I downloaded  from GitHub [zip file](https://github.com/ocelot-collab/ocelot/archive/master.zip). Now, I can run tutorials.

**Comment by hnakahara79** [comment]
Hi @st-walker,  

just last question: 
I downloaded Ocelot from from GitHub [zip file](https://github.com/ocelot-collab/ocelot/archive/master.zip), but it is working **without doing python3 setup.py install.**  

Is it OK ?  Will it make any impact on its performance ?

Thank you.

**Comment by sergey-tomin** [comment]
Hi @hnakahara79,

This will not affect its performance. We often use it this way if there is no way to clone it from GitHub. 

Sergey.

**Comment by st-walker** [comment]
`python setup.py install` is a means to put the library in your PYTHONPATH and install any dependencies.  if you already have the dependencies installed and ocelot is already in your PYTHONPATH then strictly yeah it is not necessary.  performance is unimpacted as sergey says.  if you care about performance, install jit, numba, etc (as the warnings say I think)

**Comment by hnakahara79** [comment]
Hi @sergey-tomin and @st-walker, 

thanks to both of you for quick reply and clarification. 

Best regards,
Naka
