### ISSUE TITLE
Error with injector_lattice

### ISSUE THREAD

**Issue by dmargarone** [ocelot-collab/ocelot#168]
Hi, 

When I am trying to follow the "**tutorial N2: Tracking**"   I received an error message as follows:

**from injector_lattice import *
ModuleNotFoundError: No module named 'injector_lattice'**

I did not encountered any error with "**tutorial N1: Linear optics**" but from **tutorial N2 onwards** error starts appearing. 

Could you please help me to fix the error. 

Thanks a lot.

**Comment by st-walker** [comment]
From which directory are you running it?  injector_lattice.py is in ocelot/demos/ipython_tutorials, if you are running the jupyter notebooks from elsewhere it won't be able to find this file.  I just tried it and it works for me.

**Comment by dmargarone** [comment]
Hi @st-walker , thanks your quick reply. 

Actually, I am using my old computer with Mac OS big-sur. In this, I can install Ocelot using conda. 

I am running all these tutorials in "Spyder".  I am just copying the example tutorials step-by-step and running it. In this way I am trying to follow what happens. Normally, I runs all installed python based programs on "Spyder"  and its works always. The installed packages are automatically imported by "Spyder" when invoked by import command. 

Still it is a puzzle, why this error appear ....

Tutorial N1 runs fine. Do you thinks I should re-install with conda again.

Tomorrow, I will also try to install Ocelot from repository on my ubuntu (ver. 22.04).

**Comment by dmargarone** [comment]
Hi @st-walker , 

I searched for "injector_lattice" and found that it is in the "ipython_tutorials" folder. Please, see the attached figure. How should I invoke it to be recognized by the program. 

I am using the following lines in the "Spyder":

**from copy import deepcopy

import time

# import from Ocelot main modules and functions
from ocelot import *

# import from Ocelot graphical modules
from ocelot.gui.accelerator import *

# import injector lattice
from injector_lattice import *

lat = MagneticLattice(cell, stop=None)

# initialization of Twiss object
tws0 = Twiss()
# defining initial twiss parameters
tws0.beta_x = 29.171
tws0.beta_y = 29.171
tws0.alpha_x = 10.955
tws0.alpha_y = 10.955
# defining initial electron energy in GeV
tws0.E = 0.005 

# calculate optical functions with initial twiss parameters
tws = twiss(lat, tws0, nPoints=None)**

**Comment by dmargarone** [comment]
Hi @st-walker , thank you so much for your kind reply. 

Do you think, Ocelot can be installed on Ubuntu 22.04 through repository ?

I guess, it will be easy to use Ocelot in Ubuntu or Windows ....

**Comment by st-walker** [comment]
Cloning the repository and installing with the setup.py is the most guaranteed way to work.  I only ever do it this way but I change ocelot a lot so this makes sense for me anyway.  ocelot definitely works on any linux or mac distribution.  I have no experience with windows.  I am using it on a macbook right now.

**Comment by st-walker** [comment]
no problem just follow these simple instructions:

https://github.com/ocelot-collab/ocelot#github

It's how anyone developing ocelot will install ocelot.  I know it works.

**Comment by dmargarone** [comment]
Thank you @st-walker , I will let you know the status tomorrow.

**Comment by dmargarone** [comment]
Hi @st-walker , good news .... I found the way. I just need to include the corresponding folders as follows:

** from ocelot.demos.ipython_tutorials.injector_lattice import * **

Now, I know how to do with conda. ( However, I will also try to install in linux with cloning the repository).
