### ISSUE TITLE
2. Tracking in first and second order approximation without any collective effects

### ISSUE THREAD

**Issue by dmargarone** [ocelot-collab/ocelot#170]
Dear Developers,

Sorry for asking question again. Actually, I am try to run:   **2. Tracking in first and second order approximation without any collective effects** , for this I need the electron beam distribution from astra (as mentioned in the tutorial documentation). But I am  unable to locate the file. 

Please, could you let me know from where I can download the **beam_130MeV.ast**  or   **sc_beam.npz**

Thank you and sorry for bothering.

**Comment by st-walker** [comment]
sc_beam.npz is in ocelot/demos/ipython_tutorials

**Comment by dmargarone** [comment]
Hi @st-walker , thank you for super quick response. I am afraid that it is not with the conda installation. Please, see the attached screen shot. I also made complete search on my computer but no such file was found. 

<img width="811" alt="Screen Shot" src="https://github.com/ocelot-collab/ocelot/assets/88077574/cbbc3915-6a67-4819-ad99-3cc8df6e1a65">

**Comment by dmargarone** [comment]
Hi @st-walker , eventually I downloaded the file (by downloading the zip folder) and copied in my directory. Now, I can proceed further. 

Thank you so much for your help.
