### ISSUE TITLE
Conda install issues

### ISSUE THREAD

**Issue by irgallard** [ocelot-collab/ocelot#172]
Hello, 

I am having issues installing Ocelot via Conda. This is what I get:
![image](https://github.com/ocelot-collab/ocelot/assets/115991988/a7076552-0db1-45ee-9e5e-905c84ac2b30)

Hopefully there is a solution, since Conda is very easy to manage. Will try the repo install now.

**Comment by dmargarone** [comment]
Hi @irgallard, it is better to downloaded Ocelot from from GitHub [zip file](https://github.com/ocelot-collab/ocelot/archive/master.zip) and start using it directly (without any installation). 

Conda installation is handy, however, working with the downloading folder from the GitHub zip file is equally simple. Just don't forget to do: export PYTHONPATH=/your_working_dir/ocelot-master:$PYTHONPATH

**Comment by st-walker** [comment]
You can always do `pip install ~/path/to/ocelot` or `pip install --editable ~/path/to/ocelot`  This is generally easier than playing with PYTHONPATH (I have not touched PYTHONPATH in many many years).  This way also takes care of any dependencies/setup as well.

I don't know why the conda recipe doesn't work.  That is @sergey-tomin's domain.

**Comment by irgallard** [comment]
Thank you @dmargarone @st-walker. I managed to run it downloading the repo, so far it works.  One last thing, any plans to release an Ocelot docker image?

**Comment by st-walker** [comment]
It is not hard to do but I am curious what you would have in mind for it?

**Comment by irgallard** [comment]
@st-walker 
Regarding the Docker image, I think it would be nice to have a protable, isolated and compatible version of the simulator that can be deployed anywhere easily. Many applications now allow you to install with Docker for its simplicity and in case the other installation methods fail.

**Comment by irgallard** [comment]
@st-walker Thanks for the replies!

The end goal of our work is to study Reinforcement Learning algorithms applied to accelerator control, using Ocelot as environment and Kubeflow for managing the Machine Learning pipelines.  I am not an expert on Kubeflow, but as far as I understood, each element of the pipeline is typically encapsulated as a container. 

So far so good though, Ocelot works just fine on my machine and  I am  still learning to use it.
