### ISSUE TITLE
Wrong equation for relativistic beta used in undulator matrix

### ISSUE THREAD

**Issue by st-walker** [ocelot-collab/ocelot#177]
Hi friends,

[in ocelot/cpbd/elements/undulator_atom.py:
](https://github.com/ocelot-collab/ocelot/blob/1e6cb91202d02b3bdaf6d9b8d2da9adc6662c030/ocelot/cpbd/elements/undulator_atom.py#L114)

this is wrong (beta > 1):

                beta = 1 / np.sqrt(1.0 - 1.0 / (gamma * gamma))

it should be  (beta < 1)

                beta = np.sqrt(1.0 - gamma**-2)

I tried changing this myself but all the tests fail because the reference values for various matrices are now wrong (only by a bit).  I don't know how to update these reference files so I will just leave it for a real expert to fix.

**Comment by sergey-tomin** [comment]
Hi Stuart,

Thank you for finding this strange error/misprint. I don't know how or when it happened. I checked other elements and everything is fine there. Fortunately, this wrong formula only gives a small error in most cases. I have fixed and updated the unittests
