### ISSUE TITLE
The number of transfer matrix not match the number of elements

### ISSUE THREAD

**Issue by ReidarQin** [ocelot-collab/ocelot#192]
Hi Sergey, 
I found that when using lat.transfer_maps() and lat.sequence() gives different length of outcome (see the quote below). The reason of doing this is that I want to plot s versus transfer matrix element, e.g. R56, so I need a consistent outcome length. You have a second loop in transfer_maps() calculation for some dipoles etc, which causes longer output for matrix than sequence. 

Perhaps you can add s as part of the output when output_at_each_step is enabled?

> len(lat.transfer_maps(energy=14, output_at_each_step=True)[1])
> Out[262]: 1013
> 
> len(lat.sequence)
> Out[263]: 971

Best,
WQ

**Comment by st-walker** [comment]
Isn't this just because of dipole fringe fields?  Or am I missing something?

**Comment by cr-xu** [comment]
I would say this is probably due to the fact that ocelot automatically expands the `Dipole` to a `[Edge, Dipole, Edge]` sequence with edge focusing effects. Not sure if that's all though.

**Comment by sergey-tomin** [comment]
done, see CHANGELOG and commit https://github.com/ocelot-collab/ocelot/commit/982a67c1c66d2a8cac6b823f2fe3bdabe0c0c1e3
