### ISSUE TITLE
Saving beam data

### ISSUE THREAD

**Issue by laxmisubramanyam** [ocelot-collab/ocelot#200]
Hi,  
Thanks for the excellent code !!   
Could you let me know how I can save the complete phase space information of the beam (3 - position coordinates, 3 - momentum coordinates and charge) ?  I want to work with my own post-processing for visualization.

Thanks,
Laxmi

**Comment by st-walker** [comment]
```from ocelot import *

parray = ParticleArray(n=1) # Or whatever ...
save_particle_array("parray.npz", parray)

```

`parray.npz' is then just a compressed numpy `.npz`. format and can be loaded completely independently of OCELOT using `np.load`.  Or just reload into a `ParticleArray` instance using `load_particle_array`.  That's it

**Comment by st-walker** [comment]
it makes an array of 1 particle.  it was just example.  i assumed you have your own particle array from elsewhere.  I only included it so that it is code that will run.

**Comment by laxmisubramanyam** [comment]
Thanks @st-walker
