### ISSUE TITLE
making Chicane set up

### ISSUE THREAD

**Issue by dmargarone** [ocelot-collab/ocelot#223]
Dear Developers,

I want to use Chicane for beam compressor. Please, can you help me to know how I can do it in OCELOT.
I want to start with a simple example, like I have a chirped electron beam and then compressing it with the use of a Chicane set up.

Thanks a lot in advance.
DM

**Comment by sergey-tomin** [comment]
Hi,

One of the tutorials includes a simple example of beam compression. Although it is mainly about another subject but first part dedicated to chicane and beam compression. 
 https://nbviewer.org/github/ocelot-collab/ocelot/blob/master/demos/ipython_tutorials/9_thz_source.ipynb 

cheers,
Sergey.

**Comment by dmargarone** [comment]
Hi @sergey-tomin ,

I have a question about "Dx" and "x" variable in the plots (following the tutorials).

I made a small run with chicane as defined below. 

Could you please help me to understand what is the meaning of Dx ??
I think x / y are the transverse coordinates of the beam ... is it correct ??

Why beta_x and beta_y shape is different in the two plots generated by this piece of code ? (I have also attached the two figures ploted by the command used in the following piece of code)

``
# lattice

ang_value = 0.5

b1 = Bend(l = 0.2, angle = -ang_value,  e1 = 0.0, e2 = -ang_value,   tilt = 0., eid= "b")
b2 = Bend(l = 0.2, angle = ang_value, e1 = ang_value, e2 = 0.0,  tilt = 0., eid= "b")
b3 = Bend(l = 0.2, angle = ang_value, e1 = 0.0, e2 = ang_value,  tilt = 0., eid= "b")
b4 = Bend(l = 0.2, angle = -ang_value,  e1 = -ang_value, e2 = 0.0,   tilt = 0., eid= "b")
d1 = Drift(l=0.5)
d2 = Drift(l=0.5)

cell = [Marker(eid="m1"), Drift(l=0.1), b1, d1, b2, d2, b3, d1, b4,Drift(l=0.1), Marker(eid="m2")]
#cell = [Marker(eid="m1"), d1, Marker(eid="m2")]

method = {'global': SecondTM}

lat = MagneticLattice(cell, method=method)
``

``
plot_opt_func(lat, tws_echo, fig_name=0, legend=False)
``

``
x = [tw.x for tw in tws_track]
sigma_x = np.sqrt([tw.xx for tw in tws_track])
y = [tw.y for tw in tws_track]
sigma_y = np.sqrt([tw.yy for tw in tws_track])
s = [tw.s for tw in tws_track]
``

``
plot_opt_func(lat, tws_track, top_plot=["x","y"], fig_name=1, legend=False)
``

<img width="881" alt="Screenshot 2024-04-04 at 10 17 00 PM" src="https://github.com/ocelot-collab/ocelot/assets/88077574/21078abc-e20a-4d42-8129-ef6a7f2d25e3">
<img width="879" alt="Screenshot 2024-04-04 at 10 16 41 PM" src="https://github.com/ocelot-collab/ocelot/assets/88077574/c7c5c04f-adfe-4160-a1e7-bef4a9ee4ea0">

**Comment by sergey-tomin** [comment]
HI,

Dx is horizontal dispersion. 
>> I think x / y are the transverse coordinates of the beam ... is it correct ?? 
it is correct. 

Why is betas are different on two plots? maybe it is because 'tws_echo' and 'tws_track' are different.  It is impossible to determine conclusively based on the information provided.

**Comment by dmargarone** [comment]
Hi @sergey-tomin ,

Thank you for the prompt reply. I have attached a very preliminary chicane configuration. 
Please, could you help me to understand the three figures generated in this script. I have three basic questions: 

(1) why Dx in figure 1 is different that from figure 2.
(2) why beta_x and beta_y are different figure 1 and 2 or 3.
(3) why y is not changing but only x coordinate change in figure 3.

Thank you.

Best regards,
DM

[Test_simple_chicane.txt](https://github.com/ocelot-collab/ocelot/files/14885902/Test_simple_chicane.txt)

**Comment by dmargarone** [comment]
Hi @sergey-tomin ,

OK, now I understand answer of my question (3):  why only x-coordinate is changing but not y. It is because the dispersion or deflection by magnetic field only affect position along x-direction [v X B force]).

But, please could you help me to understand question (1) and (2)

Thank you.
DM
