### ISSUE TITLE
function matching

### ISSUE THREAD

**Issue by SchroederSa** [ocelot-collab/ocelot#224]
Is there a convenient way to match the beamline for a particular function?
More explicitly, I would like to minimize chromaticity or even the chromatic amplitude at a certain point of a beamline. The first is a pure analytic problem that could be solved on paper. However, minimizing the chromaticity amplitude requires a more diligent treatment and proper beam tracking - especially when LSC kicks in.
Thanks for your help!
Sarah

**Comment by sergey-tomin** [comment]
Hi Sarah,

We have a matching function which can be used to match Twiss functions: [link](https://github.com/ocelot-collab/ocelot/blob/master/ocelot/cpbd/match.py). In case you need something different, I would recommend creating your own error function and using optimization functions from scipy.optimize to find a solution. You can find some examples in the link above, and I also have a simple tutorial where you can find another example.
https://github.com/ocelot-collab/ocelot/blob/master/demos/ipython_tutorials/accelerator_optim.ipynb

Cheers,
Sergey.

**Comment by SchroederSa** [comment]
Great, thank you, Sergey!
Sarah

**Comment by SchroederSa** [comment]
Excellent, thank you, Sergey!
Sarah

**Comment by alexanatoly** [comment]
Hi @sergey-tomin , 

I am looking for optimization of an electron bunch length. 

I found that you applied a beautiful methodology to minimize the beam size along the transverse direction (x-y plane) in this tutorial  https://github.com/ocelot-collab/ocelot/blob/master/demos/ipython_tutorials/accelerator_optim.ipynb

Is it possible to apply similar methodology for minimizing the electron beam length along the propagation direction (x-s or y-s plane) i.e. achieving a minimum bunch length from a chicane ?

Best,
Alex

**Comment by sergey-tomin** [comment]
hi @alexanatoly,

sure it is possible. just instead of quads strength you can use cavity phase and voltage and bunch compressor R56. 

Cheers,
Sergey.

**Comment by alexanatoly** [comment]
hi @sergey-tomin 

thanks for replying. I just want to optimize the beam length, trying to achieve as short as possible (I am playing with **electron beam + chicane** only). Do I still need cavity phase and voltage ?

**Comment by sergey-tomin** [comment]
Of course, you can solely use the chicane. As I mentioned earlier, you will adjust R56. In that scenario, you only have one parameter to consider, and analytics can likely be employed. I would recommend looking into tutorial N9. It covers some simple cases of a beam compressor -  https://github.com/ocelot-collab/ocelot/blob/master/demos/ipython_tutorials/9_thz_source.ipynb

**Comment by alexanatoly** [comment]
@sergey-tomin 
thanks for further comments.
