### ISSUE TITLE
Code Manual

### ISSUE THREAD

**Issue by dmargarone** [ocelot-collab/ocelot#225]
Hi, 

Is it possible to please give me the code manual. 

It will help a lot to understand many things.

Thank you.
Daniela

**Comment by st-walker** [comment]
There is no manual.  Use the tutorials instead and read the source to understand what is going on/how to use ocelot.

Tutorials: https://github.com/ocelot-collab/ocelot?tab=readme-ov-file#tutorials

**Comment by dmargarone** [comment]
OK. Thanks.
