### ISSUE TITLE
Extracting Twiss parameters

### ISSUE THREAD

**Issue by dmargarone** [ocelot-collab/ocelot#228]
Hi, 

I described a particle array as follows:

```
p_array_init = generate_parray(sigma_x=1.0e-3, sigma_tau=0.5e-3,
                               sigma_px=7e-5, energy=0.1, nparticles=20000, charge=1e-09)
```

How can I get the Twiss parameter of the electron beam corresponding to this "p_array_init".

Thank you.
Daniele

**Comment by st-walker** [comment]
`get_envelope`

**Comment by dmargarone** [comment]
@st-walker , 

Thank you. 

Daniele
