### ISSUE TITLE
Plot of energy spread

### ISSUE THREAD

**Issue by laxmisubramanyam** [ocelot-collab/ocelot#230]
Hi, 

Continuously enjoying using ocelot. However, I got stuck when I was trying to plot **dE/E** or **dp/p** along y-axis and **s** along x-axis. 

I tried like ``` dp_percent = ( p_array_init.p() / p0 ) * 100 ```  and ``` plt.scatter(p_array_init.tau()/c, dp_percent, c=dp_percent, cmap='gnuplot2') ``` Is it correct ? 
If not, any clue how to do it ?

Thanks,
Laxmi

**Comment by laxmisubramanyam** [comment]
@st-walker , in the above plot 1, the momentum of the particles ``` p_array_init.p() + p0 ``` are very close the central or mean value ```(107.83)```, however, plot 2 shows the momentum spread ``` ((p_array_init.p()) * 100) ``` up to ``` 4 % ```.

**Comment by laxmisubramanyam** [comment]
@st-walker , I think its my fault the momentum distribution of the particles should be given by ``` (p_array_init.p()*p0) + p0 ``` and not by ``` (p_array.p() + p0) ```.
can you comment please :)

**Comment by st-walker** [comment]
Yes if you go to `ParticleArray` docstring it is clear:

`p = dE/(p0*c)`
