### ISSUE TITLE
Plot of transverse phase space

### ISSUE THREAD

**Issue by dmargarone** [ocelot-collab/ocelot#231]
Dear All, 

I want to plot a figure similar to the attached one. 

Do you think the commands below is correct for making such plots ?

```
X = p_array.x()                                  # x-coordinate of particles

Px = p_array.px()                                # normalized transverse momentum of the particles

plt.scatter( X, Px, c=Px, s=3, cmap='hot')       # scatter plot
```

Thank you.
Daniela

<img width="768" alt="Screenshot 2024-04-18 at 4 22 19 PM" src="https://github.com/ocelot-collab/ocelot/assets/88077574/510f709d-fe3f-44fb-83aa-4bc7bb391099">

**Comment by sergey-tomin** [comment]
Hi,

I did not use plt.scatter for awhile but I think it is correct. you can also use function show_density(x, y) function in from ocelot.gui.accelrator (https://github.com/ocelot-collab/ocelot/blob/master/ocelot/gui/accelerator.py) 

Cheers,
Sergey.

**Comment by dmargarone** [comment]
Hi @sergey-tomin,

Thank you. I will also try your method of show_density function. 

I am taking time to learn different methods inside the code, however, I am enjoying very much your code. 

Cheers,
Daniela

**Comment by dmargarone** [comment]
Hi @sergey-tomin ,

I am not able to see the expected plot of the transverse phase space of the electron beam (x-Px or y-Py) using the plotting commands.

```
X = p_array.x()                                  # x-coordinate of particles

Px = p_array.px()                                # normalized transverse momentum of the particles

Y = p_array.y()                                  # x-coordinate of particles

Py = p_array.py()                                # normalized transverse momentum of the particles
```

I even used ```show_phase_space(p_array)``` command but there also the plot are not as I was expecting them to be.

My be you can verify it by making a test electron beam (with some divergence) and then plotting its x-px figure.

**Comment by dmargarone** [comment]
Hi @sergey-tomin ,

here is an example of the x-px plot. I was expecting a similar plot as show in the first message of this issue, but this x-px plot is very different. Please, see the attached file. Do you think there is any problem ? 

[x_Px.pdf](https://github.com/ocelot-collab/ocelot/files/15156462/x_Px.pdf)

**Comment by dmargarone** [comment]
Hi @sergey-tomin 

show density gave me different result than the expected one (shown above )

```
show_density(p_array_init.x() * 1e3, p_array_init.px() * 1e3, nbins_x=200, nbins_y=200,
                        interpolation="bilinear", xlabel='x [mm]', ylabel=r'$p_x$ [mrad]’,
                        title="", show_xtick_label=True)
```

<img width="900" alt="x_Px" src="https://github.com/ocelot-collab/ocelot/assets/88077574/8110b0bf-77e7-4b36-bfb8-80611cbd6630">

**Comment by dmargarone** [comment]
Hi @st-walker,

Hi @st-walker 

Thanks a lot for your kind reply. Even ```scatter plot``` gives the same result as obtained with ```show_density```.

I made plot with 

```
X = p_array_init.x()
Px = p_array_init.px()
plt.scatter(X,Px)
```

I am expecting that the x-Px plot should show a tilt (as shown in the first figure). I used the following electron beam distribution:

```
p_array_init = generate_parray(sigma_x=20.0e-6, sigma_y=20.0e-6, sigma_tau=0.6e-3,
                               sigma_px=5.1e-4, energy=0.055, sigma_p=3.0e-4, chirp=0.008,
                               nparticles=20000, charge=500.0e-12)
```

**Comment by sergey-tomin** [comment]
Hi,
why you are expecting tilt? scatter and show_density show the same result. There is no correlation between x and px. Function generate_parra() would introduce correlation in transverse plane if Twiss parameters are defined. But if chirp is not zero you can see correlation in longitudinal phase space (tau-p). 

![Screenshot 2024-05-01 at 19 49 04](https://github.com/ocelot-collab/ocelot/assets/7983571/352c6b3a-4229-4bd7-801c-b8ea9520979a)

**Comment by dmargarone** [comment]
Hi @st-walker,

I found a literature about beam compression and I was trying to see if I can reproduce some of the results or not. 
I have attached the literature file. I was trying to make similar figures like Fig. 2.22, Fig. 2.23, Fig. 2.24 and Fig. 2.25.

[beamcompression.pdf](https://github.com/ocelot-collab/ocelot/files/15180588/beamcompression.pdf)

**Comment by dmargarone** [comment]
Hi @st-walker, 

did you see anything wrong in Fig. 2.22, Fig. 2.23, Fig. 2.24 and Fig. 2.25. in the beamcompression.pdf file. All these plots are generated with ELEGANT code. I tried to reproduce these figures.

**Comment by dmargarone** [comment]
Hi @st-walker , 

the initial parameters are given in Table 2.6 (energy and charge are same through out the simulation: E = 55 MeV and charge 0.5 nC, as given in Table 2.2).

The momentum chirp for figures 2.22-2.30 is 10 per meter.

**Comment by st-walker** [comment]
Then your problem is that you are somehow not generating the bunch properly from Table 2.6.

Is this the code you are using?  If so, it is clear to me that it will not do it correctly:

p_array_init = generate_parray(sigma_x=20.0e-6, sigma_y=20.0e-6, sigma_tau=0.6e-3,
                               sigma_px=5.1e-4, energy=0.055, sigma_p=3.0e-4, chirp=0.008,
                               nparticles=20000, charge=500.0e-12)

You need to set the `tws` kwarg to make sure that the correlations are computed correctly when generating the beam from the Twiss parameters.

Alternatively use `cov_matrix_from_twiss` and `cov_matrix_to_parray` from the cpbd.beam module together (I wrote these two functions so I am confident that they work).

**Comment by dmargarone** [comment]
Hi @st-walker,

thank you so so much for helping. I am trying to understand these from an example:

```
from copy import deepcopy

# import from Ocelot main modules and functions
from ocelot import *

# import from Ocelot graphical modules
from ocelot.gui import *
from ocelot.gui.my_plots import *
from ocelot.gui.accelerator import *
from ocelot.cpbd.beam import cov_matrix_to_parray, cov_matrix_from_twiss

import time

# Generate an electron beam - ParticleArray 

charge = 1e-9 # 1nC
interesting_bunch_lengths = [5e-6, 15e-6, 25e-6] # 5um, 15um and 25um.
energy = 16.5 # GeV

# Emittances (equal in both x and y)
en = 1e-6
eg = en / (energy / m_e_GeV)

# Twiss parameters
beta_x = 40
beta_y = 13
alpha_x = 2.6
alpha_y = 1.0

# energy spread
sigma_p = 4e-5
cov_matrices = [cov_matrix_from_twiss(ex,
                                   ey,
                                   sigma_tau,
                                   sigma_p,
                                   beta_x=beta_x,
                                   beta_y=beta_y,
                                   alpha_x=alpha_x,
                                   alpha_y=alpha_y)
                for sigma_tau in interesting_bunch_lengths]

# Define input particle arrays, one for each covariance matrix,
# each of which correspond to a single bunch length.
parray0s = [cov_matrix_to_parray([0, 0, 0, 0, 0, 0],
                              cov_matrix,
                              energy,
                              charge,
                              nparticles=200000) for cov_matrix in cov_matrices]
```

But I received an error: ```name 'ex' is not defined```. Please, could you suggest me how to fix this error.

**Comment by st-walker** [comment]
yeah you need to define ex, which is the geometric emittance.  eg is the geometric emittance.

**Comment by dmargarone** [comment]
Hi @st-walker,

Thank you. I will proceed as you suggested. Hope I can learn something today.

**Comment by dmargarone** [comment]
Hi @st-walker,

does ```parray0s``` is the initial beam distribution in the following:

```
#**********************************************
### Generate an electron beam - ParticleArray *
#**********************************************

charge = 0.5e-9 # 1nC

energy = 0.055 # GeV

# pulse length
sigma_tau = 0.6e-3 # [in meter]

# Emittances (equal in both x and y)
en = 1e-6
eg = en / (energy / m_e_GeV)

# Twiss parameters
beta_x = 10
beta_y = 10
alpha_x = -1
alpha_y = -1

# energy spread
sigma_p = 3e-4

cov_matrices = [cov_matrix_from_twiss(ex=eg,
                                   ey=eg,
                                   sigma_tau=sigma_tau,
                                   sigma_p=sigma_p,
                                   beta_x=beta_x,
                                   beta_y=beta_y,
                                   alpha_x=alpha_x,
                                   alpha_y=alpha_y)]
#                for sigma_tau in interesting_bunch_lengths]

# Define input particle arrays, one for each covariance matrix,
# each of which correspond to a single bunch length.
parray0s = [cov_matrix_to_parray([0, 0, 0, 0, 0, 0],
                              cov_matrix,
                              energy,
                              charge,
                              nparticles=200000) for cov_matrix in cov_matrices]
```

**Comment by st-walker** [comment]
plot it!

**Comment by st-walker** [comment]
ok but what is in  the interesting_bunch_lengths?

parray0s is a list, it cnanot give what it says you give.

you can plot each one, you can track each one..  it is up to you.  if you only want one remove the list comprehension and just pick a single constant sigma_tau.

**Comment by dmargarone** [comment]
Hi @st-walker 

I don't want to repeat the example given in [https://github.com/ocelot-collab/ocelot/blob/18f64f22baa9983cc5e2e259adb44ffa9e08fa6b/demos/ipython_tutorials/parameter-scanner.ipynb#L50](url)

I want to creat a particle array from twiss parameters given above. 

from definition of ```cov_matrix_to_parray```, it appear that it should return ```the particle array```. 
If I do ```print(np.size(parray0s))``` it gives me the correct value equal to ```nparticles```.  

When I used the ```p_array_init = generate_parray( ...... )``` I can directly print the ```p_array_init``` values. And can use the ```p_array_init``` for further analysis. But here, I got stuck after 

```
parray0s = [cov_matrix_to_parray([0, 0, 0, 0, 0, 0],
                              cov_matrix,
                              energy,
                              charge,
                              nparticles=200000) for cov_matrix in cov_matrices]
```

**Comment by st-walker** [comment]
yes in Python `[x for x in Y]` notation  is a list comprehension, so here `parray0s` is a list.

**Comment by dmargarone** [comment]
Hi @st-walker 

I couldn't get it well. But let me try, if I fail I will return back to you.

**Comment by st-walker** [comment]
good luck, to be honest, it seems some of these questions are not ocelot questions but rather Python questions.  if you sit with repl (i recommend ipython) all day and go line by line I am sure you will figure it all out and learn a lot.

**Comment by dmargarone** [comment]
Thank you @st-walker. 
One question, just to avoid confusion, now ```parray0s``` is the particle distribution array ... right ?

**Comment by dmargarone** [comment]
Hi @st-walker 

I think I have a good news to share with you. Finally, I am able to reproduce the tilted figures as shown in that document. Please, see the attached figure.

All credit goes to you. You are so helpful and kind. A very big thanks to you. 

Now, only one thing is remaining. ```How to include energy or momentum chirp``` ?

![phase_space_initial](https://github.com/ocelot-collab/ocelot/assets/88077574/f8542913-67f0-4ec4-8aa5-963964a064c7)

**Comment by st-walker** [comment]
> How to include energy or momentum chirp

You have the particle array, you have the longitudinal positions of the particles `parray.tau()` and you have the momentum offsets of the particles `parray.p()` so you need to just modulate the last row (the momentum) of the `parray.rparticles` array based on each particle's longitudinal position (the second from last row of `parray.rparticles`).

**Comment by dmargarone** [comment]
Hi @st-walker,

although the concept is simple (p = p0 + chirp*tau), this part looks confusing to me. Anyways, I will try and if I get completely messed up, I may need your advice again.

**Comment by dmargarone** [comment]
Hi @st-walker,

Maybe now I could follow your suggestion. I did as follows:

```
chirp = 0.001

# pulse length
sigma_tau = 0.6e-3   # [in meter]

p_array_init.rparticles[5] = p_array_init.rparticles[5] + (chirp * p_array_init.rparticles[4] / sigma_tau)
```
**Is it correct ?**   the result is attached below

![phase_space_initial_chirp](https://github.com/ocelot-collab/ocelot/assets/88077574/00c695e7-6fe7-4051-99e9-00d56c5792ef)

**Comment by dmargarone** [comment]
Hi @st-walker  @sergey-tomin ,

Thank you so much to both of you for being so kind and helpful every time. 

with lots of best wishes,
Daniela
