### ISSUE TITLE
Using CSR with space-charge

### ISSUE THREAD

**Issue by laxmisubramanyam** [ocelot-collab/ocelot#233]
Hi, Is it possible to apply both CSR and Space-charge together ?

If I have 
```
sc1 = SpaceCharge()
sc1.nmesh_xyz = [63, 63, 63]
sc1.step = 0.01

csr = CSR()
csr.traj_step = 0.0002
csr.apply_step = 0.0005

navi = Navigator(lat)
```

the following command work (one at a time)

```
navi.add_physics_proc(csr, lat.sequence[0], lat.sequence[-1])
navi.add_physics_proc(sp1, lat.sequence[0], lat.sequence[-1])
```

**but I want to use both csr and sc1, how to use them together ?**

Thanks in advance.

**Comment by st-walker** [comment]
Yes.  What you are doing uses both.

**Comment by laxmisubramanyam** [comment]
Hi @st-walker

Thanks for help.

Best regards,
Laxmi
