### ISSUE TITLE
What is the correct way of using step size in space-charge function

### ISSUE THREAD

**Issue by laxmisubramanyam** [ocelot-collab/ocelot#246]
Hi @sergey-tomin @st-walker

It's quite strange that if I use:

```
sc = SpaceCharge()
sc.nmesh_xyz = [63, 63, 63]
sc.step = 0.1
navi.unit_step = 0.5 # m
```

I get one result, however, If I use:

```
sc = SpaceCharge()
sc.nmesh_xyz = [63, 63, 63]
sc.step = 1
navi.unit_step = 0.05 # m
```

I get different result. 

I understand that final step size is ```sc.step * navi.unit_step```. Both are same in the two examples, then why the results are different ?

**What is the correct way of using space charge step ?**

**Comment by sergey-tomin** [comment]
Hi, 
the step should be integer number (1,2,3...) the minimum possible step is defined by Navigator.unit_step. if you want to reduce step you have to reduce Navigator.unit_step. In next release I will introduce warning to prevent this.

**Comment by laxmisubramanyam** [comment]
Hi @sergey-tomin 

Thanks for the clarification. 

Best regards,
Laxmi
