### ISSUE TITLE
nPoints of twiss output in tracking function

### ISSUE THREAD

**Issue by SchroederSa** [ocelot-collab/ocelot#258]
Hi, 

Is there a way to increase the number of nPoints, i.e. the number of s-evaluations for the tracking twiss output?

I'd like to have tws_track being more granular sampled for nicer plotting:
 tws_track, p_array = track(triplet.lat, p_array, navi, print_progress=False)

I saw that it works through the envelope calculations, but I couldn't find any handle to increase the stepping output.

In the attached plot, I added an aperture at the s-location of the black dotted line. Given the limited s-sampling of tws_track the first bit of sigma up to the aperture is incorrectly depicted.

Thanks!
Sarah

<img width="875" alt="Screenshot 2024-08-29 at 2 40 12 AM" src="https://github.com/user-attachments/assets/025fcdcb-56f3-4562-acaa-7de7fa57b3a1">

**Comment by SchroederSa** [comment]
To illustrate what I mean. Here, I added an infinitesimal short drift just in front of the aperture:

<img width="881" alt="Screenshot 2024-08-29 at 2 56 19 AM" src="https://github.com/user-attachments/assets/b6f9a9e8-3b1b-4386-b030-2de39d3e86cd">

**Comment by st-walker** [comment]
If you look at the code `track` is calculating the twiss at every step given by the navigator.  So based on this, I would suggest decreasing the navigator unit step.  If this results in too much of a slow down, scale the corresponding steps of all your physics processes, then add an empty proc with a `step = 1`.  I'm not sure I've done this but I think it should work.  The idea anyway should be clear: force the navigator to go in smaller steps.

**Comment by SchroederSa** [comment]
Ok, thanks. So far, I don't have any physics processes included.

**Comment by st-walker** [comment]
Then add an emptyproc to force the navigator to take small steps and set the unit step of the navigator as small as you like.

**Comment by SchroederSa** [comment]
Great, thanks for the quick help!

for reference:

`
'
navi = Navigator(lat)
navi.activate_apertures()
ep = EmptyProc()
ep.step=0.1
navi.add_physics_proc(ep, lat.sequence[1], triplet.lat.sequence[-2])
navi.unit_step = 0.1
tws_track, p_array = track(.lat, p_array, navi, print_progress=False)
`

Although I still have the infinitesimal dummy drift just before the aperture, it allows me to have a larger step value and doesn't falsify the result.

<img width="864" alt="Screenshot 2024-08-29 at 3 54 39 AM" src="https://github.com/user-attachments/assets/b0193008-753c-440e-81e0-b14d7c8652a1">

**Comment by SchroederSa** [comment]
Thanks!

**Comment by st-walker** [comment]
In principle `step` should be an integer (it is dimensionless).   The physics process is applied every `step*Navigator.unit_step`, so `Navigator.unit_step` defines the increment step forward taken by the ParticleArray, so it is units of metres.  I don't know what impact it has in this case, though.   I don't know what happens if you pick a float step and particularly if you pick a physics process step <1.
