### ISSUE TITLE
add_physics_proc terminates at start-position of stop_element

### ISSUE THREAD

**Issue by SchroederSa** [ocelot-collab/ocelot#260]
Hi,

 I plotted the 'lattice sigma' and the tracked sigma. As discussed in a previous issue, I was referred to use an EmptyProc() for making the evolution depicted more accurately in the elements, i.e. Quads. Doing so, I realised that the add_physics_process(process, start_element, stop_element) applies the empty physics process only to the start position of the stop_element. 

For some illustration:

```python
        navi = Navigator(lat)
        ep = EmptyProc()
        ep.step=1
        navi.add_physics_proc(ep, lat.sequence[1], self.lat.sequence[-1])
        navi.unit_step = 0.01
```

results in the following plot. 

<img width="370" alt="Screenshot 2024-09-04 at 4 28 18 PM" src="https://github.com/user-attachments/assets/132833e9-a68c-4c24-992c-56f79fde296f">

Meanwhile, when I add a monitor or marker at the end of the beamline, I receive this:

```python
        mon = Marker()
        lat.sequence.append(mon)
        navi = Navigator(lat)
        ep = EmptyProc()
        ep.step=1
        navi.add_physics_proc(ep, lat.sequence[1], self.lat.sequence[-1])
        navi.unit_step = 0.01
```

<img width="371" alt="Screenshot 2024-09-04 at 4 35 58 PM" src="https://github.com/user-attachments/assets/3e933e27-e6ea-4f74-89ef-202b87764bee">

Is this wanted / a feature? It is not entirely intuitive that I need an additional element to apply the physics until the end of the 'end_element'.

I am reporting this because it might be worth checking for actual physics processes. Imagine I wanted to simulate a tight focus and needed to add space charge; right now, if my finding applies to all physics processes, I would require a monitor or some element after the point of interest for correct physics modelling.

Best
Sarah

**Comment by st-walker** [comment]
@sergey-tomin

**Comment by sergey-tomin** [comment]
Yes, this is how it should work. I believe I've described it somewhere. I will repeat it in Navigator class docstring if it is not there yet. Regarding the start/stop elements, I would still suggest using markers. It will definitely eliminate any ambiguities.

**Comment by SchroederSa** [comment]
Thank you!

**Comment by SchroederSa** [comment]
Thank you
