### ISSUE TITLE
Question about magnetic triplet

### ISSUE THREAD

**Issue by jamesclarke22** [ocelot-collab/ocelot#263]
Dear Ocelot developers,

Greetings.

I am a beginner as a beamline code user. I found the tutorials very helpful and most of the time self-explanatory. 

I am trying to design a beamline using an electromagnets triplet. I am following an example script [triplet.py](https://github.com/ocelot-collab/ocelot/blob/02560bcecbea4f15e476d1119b188e5f6e0feea8/demos/ebeam/triplet.py#L4) 

Please, could you let me know the meaning of the expression: ```Q1 = Quadrupole(l = 0.3, k1 = 5)```. Does this means that the quadrupole ```length is 0.3 meters``` and ```magnetic field gradient is 5 Tesla per meter``` ?

################

**Another question:** Can we use ```Quadrupole``` for simulating ```electromagnets``` as well ?

################

Thank you.
James

**Comment by jamesclarke22** [comment]
Dear Ocelot developers,

I got answer of my first question:  in ```Q1 = Quadrupole(l = 0.3, k1 = 5)```, k1 represents quadrupole strength in ```[1/m^2]```. 

Could you please, answer my second question: ```Can we use Quadrupole for simulating electromagnet-Quadrupole as well ``` ?

**Comment by sergey-tomin** [comment]
Hi Jemes,

yes, k1 is quadrupole strength in [1/m^2]. I also recommend reviewing the code, as it often provides explanations for the meaning of each argument. For beamline design you can also have a look on Tutorial N7 - https://nbviewer.org/github/ocelot-collab/ocelot/blob/master/demos/ipython_tutorials/7_lattice_design.ipynb

Regarding the “electromagnet-Quadrupole,” if you are referring to the standard quadrupole with coils powered by a power supply, then the answer is yes. From a simulation perspective, there is no distinction between permanent magnet quadrupoles and electromagnet quadrupoles; they are treated equivalently.

Cheers,
Sergey.

**Comment by jamesclarke22** [comment]
Dear Prof. Sergey,

Thank you for the explanation. It is very helpful.

Best,
James
