### ISSUE TITLE
evaluate possibility of interfacing to the openpmd standard

### ISSUE THREAD

**Issue by iagapov** [ocelot-collab/ocelot#48]
https://github.com/openPMD

**Comment by zhangli28** [comment]
Dear All,

Is there any information or update on this issue ??  

Many popular codes like WARPX and FBPIC are using openpmd format. If loading such files directly in Ocelot is possible, then Ocelot will be a potential choice for studying beam revolution from these PIC codes.

**Comment by st-walker** [comment]
It would be an honour to be such a potential choice for beam revolution.

Openpmd is supported already and has been since 55d485d19ab7e9c3e92c09484588aa85b35a7a13

**Comment by zhangli28** [comment]
Dear @st-walker thanks for the excellent news. 

I will check how to load the electron bunch data from openpmd format to Ocelot. 

Thanks.
