### ISSUE TITLE
this difference with elegant

### ISSUE THREAD

**Issue by iagapov** [ocelot-collab/ocelot#51]
https://desycloud.desy.de/index.php/s/JPC26QZcqn2rtRy

**Comment by sergey-tomin** [comment]
To compare two structures, they must be the same. If you introduce '...., gap=0.04, fint=0.2708)' into the second dipole "ARDGMBHD2" as it is in the elegant lattice, the result will be the same.

**Comment by iagapov** [comment]
I cannot confirm that this solves the problem.
