### ISSUE TITLE
ocelot.gui.accelerator.show_density is buggy

### ISSUE THREAD

**Issue by cr-xu** [ocelot-collab/ocelot#83]
This line causes matplotlib (>3.3) to throw an error:

https://github.com/ocelot-collab/ocelot/blob/0489eaf3fb232cc4167573c51f7bd28cc3110aba/ocelot/gui/accelerator.py#L927

```
ValueError: 'low' is not a valid value for origin; supported values are 'upper', 'lower'
```

Also the deepcopy doesn't seem to work properly

https://github.com/ocelot-collab/ocelot/blob/0489eaf3fb232cc4167573c51f7bd28cc3110aba/ocelot/gui/accelerator.py#L909

causes the following warning message

``` 
.../Ocelot/ocelot/ocelot/gui/accelerator.py:910: MatplotlibDeprecationWarning: You are modifying the state of a globally registered colormap. In future versions, you will not be able to modify a registered colormap in-place. To remove this warning, you can make a copy of the colormap first. cmap = copy.copy(mpl.cm.get_cmap("rainbow"))

 my_rainbow.set_under('w')
```

**Comment by sergey-tomin** [comment]
thanks for the bug report. Fixed. Now in dev branch, soon will be in master too.
