### ISSUE TITLE
track_sections forces the beam to be centered at the beginning of each section

### ISSUE THREAD

**Issue by RandomByter** [ocelot-collab/ocelot#89]
track_sections forces the beam to be centered at the beginning of each section, in case one would like to see the orbit along the whole machine it gives incorrect results. It would be nice to have an option to switch the feature off.

**Comment by sergey-tomin** [comment]
Hi, I added this possibility to dev branch but not yet tested. Can you check? you need to put in config dictionary {"remove_offsets": False}.
